{% set name = "dbt-common" %}
{% set version = "1.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dbt_common-{{ version }}.tar.gz
  sha256: 2ec733467dab4dbf515651a9347ce71e428986ddcb91ed4c2d5084c5e9dea2e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - agate >=1.7.0,<1.10
    - colorama >=0.3.9,<0.5
    - deepdiff >=7.0,<8.0
    - isodate >=0.6,<0.7
    - jsonschema >=4.0,<5.0
    - jinja2 >=3.1.3,<4
    - mashumaro >=3.9,<4.0
    - pathspec >=0.9,<0.13
    - protobuf >=5.0,<6.0
    - python-dateutil >=2.0,<3.0
    - requests <3.0.0
    - typing_extensions >=4.4,<5.0

test:
  imports:
    - dbt_common
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dbt-labs/dbt-common
  summary: The shared common utilities that dbt-core and adapter implementations use
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/dbt
    - rxm7706
